# theme         : jekyll-theme-minimal
permalink     : /:categories/:year/:month/:title/
title         : Jonathan Gropp
description   : PhD student in Weizmann Institute, Earth and Planetary Sciences
layout        : sidebar

# Build settings
markdown      : kramdown
theme         : minima
plugins       :
  - jekyll-feed

include:
          - cv.md
