theme             : jekyll-theme-minimal
permalink         : /:categories/:year/:month/:title/
title             : Jonathan Gropp
description       : biology / geochemistry / methane / stable isotopes / numerical modeling
layout            : sidebar
link_research     : Research
link_publications : Publications

include:
          - publications.md
