theme             : jekyll-theme-minimal
permalink         : /:categories/:year/:month/:title/
title             : Jonathan Gropp
description       : biology / geochemistry / methane / stable isotopes / numerical modeling
layout            : sidebar
link_research     : Research
link_publications : Publications
link_CV           : CV

include:
          - https://drive.google.com/file/d/1QO8Bps9QcNApD8NcpHIrTMatv1qhBs_8/view?usp=sharing
          - publications.md
