theme             : jekyll-theme-minimal
permalink         : /:categories/:year/:month/:title/
title             : Jonathan Gropp
description       : Biogeochemist
layout            : sidebar
link_publications : Publications
link_CV           : CV

include:
          - cv.md
          - publications.md
