theme         : jekyll-theme-cayman
permalink     : /:categories/:year/:month/:title/
title         : My personal website
description   : Not available yet
layout        : sidebar
include:
          - cv.md
