theme             : jekyll-theme-minimal
# remote_theme      : "mmistakes/minimal-mistakes"
permalink         : /:categories/:year/:month/:title/
title             : Jonathan Gropp
description       : microbiology / geochemistry / methane / stable isotopes / numerical modeling
layout            : sidebar
link_research     : Research
link_publications : Publications

include:
          - publications.md

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-archives
#   - jekyll-paginate
#   - jekyll-seo-tag # Good one you already added!
